// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Web.Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Ensures the homepage loads
        /// </summary>
        public void Home_Page_Loads()
        {
            #region Variable Declarations
            BrowserWindow uIRegisterSponsorworksWindow = this.UIRegisterSponsorworksWindow;
            #endregion

            // Go to web page 'https://localhost:44301/'
            uIRegisterSponsorworksWindow.NavigateToUrl(new System.Uri(this.Home_Page_LoadsParams.UIRegisterSponsorworksWindowUrl));
        }
        
        /// <summary>
        /// Gets and Posts the register form
        /// </summary>
        public void Account_Register()
        {
            #region Variable Declarations
            HtmlHyperlink uIRegisterHyperlink = this.UIRegisterSponsorworksWindow.UIHomePageSponsorworksDocument.UIRegisterHyperlink;
            HtmlEdit uIEmailEdit = this.UIRegisterSponsorworksWindow.UIRegisterSponsorworksDocument.UIEmailEdit;
            HtmlEdit uIPasswordEdit = this.UIRegisterSponsorworksWindow.UIRegisterSponsorworksDocument.UIPasswordEdit;
            HtmlEdit uIConfirmpasswordEdit = this.UIRegisterSponsorworksWindow.UIRegisterSponsorworksDocument.UIConfirmpasswordEdit;
            HtmlInputButton uIRegisterButton = this.UIRegisterSponsorworksWindow.UIRegisterSponsorworksDocument.UIRegisterButton;
            #endregion

            // Click 'Register' link
            Mouse.Click(uIRegisterHyperlink, new Point(48, 4));

            // Type 'test@test.com' in 'Email' text box
            uIEmailEdit.Text = this.Account_RegisterParams.UIEmailEditText;

            // Type '{Tab}' in 'Email' text box
            Keyboard.SendKeys(uIEmailEdit, this.Account_RegisterParams.UIEmailEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.Account_RegisterParams.UIPasswordEditPassword;

            // Type '{Tab}' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.Account_RegisterParams.UIPasswordEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Confirm password' text box
            uIConfirmpasswordEdit.Password = this.Account_RegisterParams.UIConfirmpasswordEditPassword;

            // Click 'Register' button
            Mouse.Click(uIRegisterButton, new Point(33, 31));
        }
        
        #region Properties
        public virtual Home_Page_LoadsParams Home_Page_LoadsParams
        {
            get
            {
                if ((this.mHome_Page_LoadsParams == null))
                {
                    this.mHome_Page_LoadsParams = new Home_Page_LoadsParams();
                }
                return this.mHome_Page_LoadsParams;
            }
        }
        
        public virtual Account_RegisterParams Account_RegisterParams
        {
            get
            {
                if ((this.mAccount_RegisterParams == null))
                {
                    this.mAccount_RegisterParams = new Account_RegisterParams();
                }
                return this.mAccount_RegisterParams;
            }
        }
        
        public UIRegisterSponsorworksWindow UIRegisterSponsorworksWindow
        {
            get
            {
                if ((this.mUIRegisterSponsorworksWindow == null))
                {
                    this.mUIRegisterSponsorworksWindow = new UIRegisterSponsorworksWindow();
                }
                return this.mUIRegisterSponsorworksWindow;
            }
        }
        #endregion
        
        #region Fields
        private Home_Page_LoadsParams mHome_Page_LoadsParams;
        
        private Account_RegisterParams mAccount_RegisterParams;
        
        private UIRegisterSponsorworksWindow mUIRegisterSponsorworksWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Home_Page_Loads'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class Home_Page_LoadsParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'https://localhost:44301/'
        /// </summary>
        public string UIRegisterSponsorworksWindowUrl = "https://localhost:44301/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Account_Register'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class Account_RegisterParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'test@test.com' in 'Email' text box
        /// </summary>
        public string UIEmailEditText = "test@test.com";
        
        /// <summary>
        /// Type '{Tab}' in 'Email' text box
        /// </summary>
        public string UIEmailEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "w9dSfUfxSqOh1wBBi5Pzwpl5P+kOmAkE";
        
        /// <summary>
        /// Type '{Tab}' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Confirm password' text box
        /// </summary>
        public string UIConfirmpasswordEditPassword = "w9dSfUfxSqOh1wBBi5Pzwpl5P+kOmAkE";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIRegisterSponsorworksWindow : BrowserWindow
    {
        
        public UIRegisterSponsorworksWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Register - Sponsorworks";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Register - Sponsorworks");
            this.WindowTitles.Add("https://localhost:44301/");
            this.WindowTitles.Add("Home Page - Sponsorworks");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageSponsorworksDocument UIHomePageSponsorworksDocument
        {
            get
            {
                if ((this.mUIHomePageSponsorworksDocument == null))
                {
                    this.mUIHomePageSponsorworksDocument = new UIHomePageSponsorworksDocument(this);
                }
                return this.mUIHomePageSponsorworksDocument;
            }
        }
        
        public UIRegisterSponsorworksDocument UIRegisterSponsorworksDocument
        {
            get
            {
                if ((this.mUIRegisterSponsorworksDocument == null))
                {
                    this.mUIRegisterSponsorworksDocument = new UIRegisterSponsorworksDocument(this);
                }
                return this.mUIRegisterSponsorworksDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageSponsorworksDocument mUIHomePageSponsorworksDocument;
        
        private UIRegisterSponsorworksDocument mUIRegisterSponsorworksDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIHomePageSponsorworksDocument : HtmlDocument
    {
        
        public UIHomePageSponsorworksDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - Sponsorworks";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://localhost:44301/";
            this.WindowTitles.Add("Home Page - Sponsorworks");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIRegisterHyperlink
        {
            get
            {
                if ((this.mUIRegisterHyperlink == null))
                {
                    this.mUIRegisterHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "registerLink";
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Register";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Register";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://localhost:44301/Account/Register";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"registerLink\" href=\"/Account/Registe";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIRegisterHyperlink.WindowTitles.Add("Home Page - Sponsorworks");
                    #endregion
                }
                return this.mUIRegisterHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIRegisterHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIRegisterSponsorworksDocument : HtmlDocument
    {
        
        public UIRegisterSponsorworksDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Register - Sponsorworks";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Register";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://localhost:44301/Account/Register";
            this.WindowTitles.Add("Register - Sponsorworks");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Email";
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Email\" class=\"form-control\" id=\"Em";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIEmailEdit.WindowTitles.Add("Register - Sponsorworks");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"form-control\" id=";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIPasswordEdit.WindowTitles.Add("Register - Sponsorworks");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlEdit UIConfirmpasswordEdit
        {
            get
            {
                if ((this.mUIConfirmpasswordEdit == null))
                {
                    this.mUIConfirmpasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIConfirmpasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ConfirmPassword";
                    this.mUIConfirmpasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ConfirmPassword";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Confirm password";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ConfirmPassword\" class=\"form-contr";
                    this.mUIConfirmpasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIConfirmpasswordEdit.WindowTitles.Add("Register - Sponsorworks");
                    #endregion
                }
                return this.mUIConfirmpasswordEdit;
            }
        }
        
        public HtmlInputButton UIRegisterButton
        {
            get
            {
                if ((this.mUIRegisterButton == null))
                {
                    this.mUIRegisterButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIRegisterButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIRegisterButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIRegisterButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Register";
                    this.mUIRegisterButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIRegisterButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIRegisterButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIRegisterButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\" va";
                    this.mUIRegisterButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "5";
                    this.mUIRegisterButton.WindowTitles.Add("Register - Sponsorworks");
                    #endregion
                }
                return this.mUIRegisterButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIEmailEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlEdit mUIConfirmpasswordEdit;
        
        private HtmlInputButton mUIRegisterButton;
        #endregion
    }
}
