// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Web.Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Ensures the homepage loads
        /// </summary>
        public void Home_Page_Loads()
        {
            #region Variable Declarations
            BrowserWindow uIRegisterSponsorworksWindow = this.UIRegisterSponsorworksWindow;
            #endregion

            // Go to web page 'https://localhost:44301/'
            uIRegisterSponsorworksWindow.NavigateToUrl(new System.Uri(this.Home_Page_LoadsParams.UIRegisterSponsorworksWindowUrl));
        }
        
        #region Properties
        public virtual Home_Page_LoadsParams Home_Page_LoadsParams
        {
            get
            {
                if ((this.mHome_Page_LoadsParams == null))
                {
                    this.mHome_Page_LoadsParams = new Home_Page_LoadsParams();
                }
                return this.mHome_Page_LoadsParams;
            }
        }
        
        public UIRegisterSponsorworksWindow UIRegisterSponsorworksWindow
        {
            get
            {
                if ((this.mUIRegisterSponsorworksWindow == null))
                {
                    this.mUIRegisterSponsorworksWindow = new UIRegisterSponsorworksWindow();
                }
                return this.mUIRegisterSponsorworksWindow;
            }
        }
        #endregion
        
        #region Fields
        private Home_Page_LoadsParams mHome_Page_LoadsParams;
        
        private UIRegisterSponsorworksWindow mUIRegisterSponsorworksWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Home_Page_Loads'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class Home_Page_LoadsParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'https://localhost:44301/'
        /// </summary>
        public string UIRegisterSponsorworksWindowUrl = "https://localhost:44301/";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIRegisterSponsorworksWindow : BrowserWindow
    {
        
        public UIRegisterSponsorworksWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Register - Sponsorworks";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Register - Sponsorworks");
            this.WindowTitles.Add("https://localhost:44301/");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
    }
}
